### ISSUE TITLE
Revert https://github.com/frozzare/go-swish/pull/5

### ISSUE THREAD

**Issue by ptomasroos** [frozzare/go-swish#6]
Now the endpoint on test has been updated again.
I'm pretty sure swish unintended deployed a number instead to the test api.

Tried as well on the production api and it requires a string and returns a string as expected.
So we should revert it. 

https://github.com/frozzare/go-swish/pull/5

@frozzare

**Comment by frozzare** [comment]
Yeah that's sounds about right. Done https://github.com/frozzare/go-swish/commit/c4c8777889d46f011749f07ed04e7211498288a7
